# This is a generated file. Not intended for manual editing.
services:
  simplenotes.api:
    build:
      context: "C:\\Users\\Jorik Mantana\\WebNotes\\backend"
      dockerfile: "SimpleNotes.API/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/SimpleNotes.API.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "simplenotes.api:dev"
    ports: []
    volumes:
    - "C:\\Users\\Jorik Mantana\\WebNotes\\backend\\SimpleNotes.API:/app:rw"
    - "C:\\Users\\Jorik Mantana\\WebNotes\\backend:/src:rw"
    - "C:\\Users\\Jorik Mantana\\.nuget\\packages:/home/app/.nuget/packages"
    working_dir: "/app"
